# Generated by Django 5.1.3 on 2025-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.IntegerField(choices=[('Python 3.11.2', 109), ('Python 3.12.5', 100), ('Python 3.8.1', 71), ('C++ (Clang 7.0.1)', 76), ('C (GCC 14.1.0)', 103), ('Java (OpenJDK 13.0.1)', 62), ('JavaScript (Node.js 18.15.0)', 93)]),
        ),
    ]
