# Generated by Django 5.1.3 on 2025-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_submission_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('statement', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit', models.IntegerField(default=256)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], db_index=True, max_length=50)),
                ('points', models.IntegerField(default=100)),
                ('editorial', models.TextField(blank=True, help_text='Solution explanation and approach', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured problems appear on the homepage')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this problem has been viewed')),
                ('solve_count', models.PositiveIntegerField(default=0, help_text='Number of unique users who solved this problem')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of unique users who attempted this problem')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='practice_problems', to='cms.problemtag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['difficulty', 'points'], name='cms_practic_difficu_c72dbe_idx'), models.Index(fields=['is_visible'], name='cms_practic_is_visi_944e26_idx'), models.Index(fields=['is_featured'], name='cms_practic_is_feat_ddf949_idx'), models.Index(fields=['view_count'], name='cms_practic_view_co_969385_idx'), models.Index(fields=['solve_count'], name='cms_practic_solve_c_b15404_idx'), models.Index(fields=['attempt_count'], name='cms_practic_attempt_e1b002_idx')],
            },
        ),
    ]
