# Generated by Django 5.1.3 on 2025-04-14 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_practiceproblem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.IntegerField(choices=[(109, 'Python 3.11.2'), (100, 'Python 3.12.5'), (71, 'Python 3.8.1'), (76, 'C++ (Clang 7.0.1)'), (103, 'C (GCC 14.1.0)'), (62, 'Java (OpenJDK 13.0.1)'), (93, 'JavaScript (Node.js 18.15.0)')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Compilation Error', 'Compilation Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], db_index=True, default='Pending', max_length=50)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('penalty', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cms.practiceproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='cms_practic_user_id_5f62d6_idx'), models.Index(fields=['status', 'submitted_at'], name='cms_practic_status_f4e00d_idx')],
            },
        ),
    ]
