# Generated by Django 5.1.3 on 2025-04-15 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_practicesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='cms.practiceproblem')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSubmissionTestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], default='Accepted', max_length=50)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='cms.practicesubmission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cms.practicetestcase')),
            ],
        ),
        migrations.AddIndex(
            model_name='practicetestcase',
            index=models.Index(fields=['problem', 'is_sample'], name='cms_practic_problem_5d7aed_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesubmissiontestcase',
            index=models.Index(fields=['submission', 'status'], name='cms_practic_submiss_3ba1c9_idx'),
        ),
    ]
