# Generated by Django 5.1.3 on 2025-04-16 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_practicetestcase_practicesubmissiontestcase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('training', 'Training'), ('resource', 'Resource'), ('contest', 'Contest')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional link to external resource', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured announcements appear at the top'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Visible to all users'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type'], name='cms_announc_announc_7a4b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_featured'], name='cms_announc_is_feat_942dff_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='cms_announc_created_83257d_idx'),
        ),
    ]
